version: "1.0"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  employee-rest:
    image: com.peopleflow/employee-rest:1.0-SNAPSHOT
    container_name: employee-rest
    ports:
      - "8081:8081"
#    environment:
#      - "SPRING_PROFILES_ACTIVE=doc"

  employee-service:
    image: com.peopleflow/employee-service:1.0-SNAPSHOT
    container_name: employee-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
#      - db
#    environment:
#      - "SPRING_PROFILES_ACTIVE=doc"