version: "1.0"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  db:
    image: docker.io/postgres:alpine
    volumes:
      - "postgres_data:/peopleflow"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: peopleflow

  employee-state-service:
    image: com.peopleflow/employee-state-service:1.0-SNAPSHOT
    container_name: peopleflow-employee-state-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - db
  employee-rest:
    image: com.peopleflow/employee-rest:1.0-SNAPSHOT
    container_name: employee-rest
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - employee-state-service
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  postgres_data:
    driver: local