server:
  port: 8081
kafka:
  employee:
    topic: employee
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://db:5432/peopleflow
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      client-id: api
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer